# Config File to Store CAEN Information
[CAEN_INFO]
Name = "Detector"
System_Type = "SY5527"
Slot = 3

[Link]
link_type1 = "TCPIP"
IP_Address = "192.XXX.XXX.XXX"
username = "username"
password = "password"

[Detector_Info]
isTGEM = true
Layer = 1
